runtime: nodejs10

readiness_check:
  path: '/readiness_check'
  check_interval_sec: 3600
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: '/liveness_check'
  check_interval_sec: 3600
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2
  initial_delay_sec: 300